import { Route, Routes } from 'react-router-dom'
import Home from '../pages/Home'
import Login from '../pages/Login'
import Register from '../pages/Register'
import Dashboard from '../pages/Dashboard'
import AIChatPage from '../pages/AIChatPage'
import RecommendationPage from '../pages/RecommendationPage'
import ClaimsPage from '../pages/ClaimsPage'
import NotificationsPage from '../pages/NotificationsPage'
import ProfilePage from '../pages/ProfilePage'
import SettingsPage from '../pages/SettingsPage'
import AdminPage from '../pages/AdminPage'
import PlaceholderPage from '../pages/PlaceholderPage'

const pageConfig = [
  { path: '/chat', title: 'AI Chat', description: 'Interact with the AI assistant for conversational policy guidance and claim support.' },
  { path: '/recommendation', title: 'Recommendation', description: 'Review personalized policy recommendations generated by the AI engine.' },
  { path: '/claims', title: 'Claims', description: 'Track claims progress and prepare required documentation with AI assistance.' },
  { path: '/notifications', title: 'Notifications', description: 'Stay on top of alerts and system messages from the AI assistant.' },
  { path: '/profile', title: 'Profile', description: 'Manage your profile, preferences, and security settings for the AI assistant.' },
  { path: '/settings', title: 'Settings', description: 'Configure account settings, preferences, and system behavior.' },
  { path: '/admin', title: 'Admin', description: 'Access administrative controls for policies, users, and system configuration.' },
]

export default function AppRoutes() {
  return (
    <Routes>
      <Route path="/" element={<Home />} />
      <Route path="/login" element={<Login />} />
      <Route path="/register" element={<Register />} />
      <Route path="/dashboard" element={<Dashboard />} />
      <Route path="/chat" element={<AIChatPage />} />
      <Route path="/recommendation" element={<RecommendationPage />} />
      <Route path="/claims" element={<ClaimsPage />} />
      <Route path="/notifications" element={<NotificationsPage />} />
      <Route path="/profile" element={<ProfilePage />} />
      <Route path="/settings" element={<SettingsPage />} />
      <Route path="/admin" element={<AdminPage />} />
      {pageConfig.map((page) => (
        <Route
          key={page.path}
          path={page.path}
          element={<PlaceholderPage title={page.title} description={page.description} route={page.title} />}
        />
      ))}
    </Routes>
  )
}
